CREATE TABLE IF NOT EXISTS tb_User
(
    UserId   VARCHAR(36)  NOT NULL DEFAULT UUID(),
    Username VARCHAR(255) NOT NULL,
    Email    VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserId)
);