CALL pr_CreateExpenseCategory('Groceries', @groceriesId);
CALL pr_CreateExpenseCategory('Toiletries', @toiletriesId);
CALL pr_CreateExpenseCategory('Rent', @rentId);
CALL pr_CreateExpenseCategory('Home loan repayments', @homeLoanId);
CALL pr_CreateExpenseCategory('Utilities', @utilitiesId);
CALL pr_CreateExpenseCategory('Bank charges', @bankChargeId);
CALL pr_CreateExpenseCategory('Vehicle payments', @vehiclePaymentId);
CALL pr_CreateExpenseCategory('Entertainment', @entertainmentId);
CALL pr_CreateExpenseCategory('Transport & Fuel', @fuelId);
CALL pr_CreateExpenseCategory('Cash', @cashId);
CALL pr_CreateExpenseCategory('Eating out', @eatingOutId);
CALL pr_CreateExpenseCategory('Takeout', @takeoutId);
CALL pr_CreateExpenseCategory('Internet', @internetId);
CALL pr_CreateExpenseCategory('Cellphone', @cellphoneId);
CALL pr_CreateExpenseCategory('Clothing', @clothingId);
CALL pr_CreateExpenseCategory('Alcohol', @alcoholId);
CALL pr_CreateExpenseCategory('Electronics', @electronicsId);
CALL pr_CreateExpenseCategory('Appliances', @appliancesId);
CALL pr_CreateExpenseCategory('Furniture', @furnitureId);
CALL pr_CreateExpenseCategory('Leisure & Sport', @sportId);
CALL pr_CreateExpenseCategory('Account transfers', @transfersId);
CALL pr_CreateExpenseCategory('Income', @incomeId);