name: CI

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'

env:
    MAJOR_VERSION: 1
    MINOR_VERSION: 0
    PATCH_VERSION: 0
    BUILD_VERSION: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.${GITHUB_RUN_NUMBER}
    BRANCH_NAME: ${GITHUB_REF#refs/heads/}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Define build number
      id: define_build_number
      run: |
        buildNumber=$(echo ${{ env.BUILD_VERSION }})
        branchName=$(echo ${{ env.BRANCH_NAME }} | sed 's:.*/::')
        buildId=$buildNumber-$branchName
        if [[ "$branchName" == "master" ]] || [[ "$branchName" == "main" ]]; then
          buildId=$buildNumber
        fi
        echo $buildNumber
        echo $branchName
        echo $buildId
        echo "##[set-output name=BUILD_NUMBER;]$(echo $buildId)"

    - name: Build & push Docker image
      working-directory: .
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker build -t krylixza/financialpeace-database:${{ steps.define_build_number.outputs.BUILD_NUMBER }} . --build-arg ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
        docker push krylixza/financialpeace-database:${{ steps.define_build_number.outputs.BUILD_NUMBER }}
        docker logout